### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by tchereau** [TrungNguyen1909/qemu-t8030#15]
Machine : macbook m1

command used:
`brew install libtasn1 meson ninja pixman lzfse jtool2 jq`

`git clone --recursive https://github.com/TrungNguyen1909/qemu-t8030`
`cd qemu-t8030`
`mkdir build; cd build`
`../configure --target-list=aarch64-softmmu,x86_64-softmmu --disable-capstone --disable-slirp
make -j$(nproc)`

configure [result](https://pastebin.com/3excArgA)

make [result](https://pastebin.com/8tf8Gjjj)

**Comment by TrungNguyen1909** [comment]
I updated the wiki, the changes are before the Get iOS firmware section.

Please try again and report the result.

**Comment by tchereau** [comment]
it's worked thanks
<img width="399" alt="Capture d’écran 2022-03-03 à 23 50 54" src="https://user-images.githubusercontent.com/78658872/156666252-64fe9035-938f-4a92-b9f4-879d27155a1c.png">
