### ISSUE TITLE
Dependencies not included in brew install command for macOS

### ISSUE THREAD

**Issue by katagaki** [TrungNguyen1909/qemu-t8030#24]
### ERROR: glib-2.56 gthread-2.0 is required to compile QEMU

`glib` seems to be required to compile QEMU, it might be good to add `glib` to the `brew install` command in the [Bringing up the emulator](https://github.com/TrungNguyen1909/qemu-t8030/wiki/Bringing-up-the-emulator) guide.

### zsh: command not found: wget

In the **Getting precompiled system binaries** section, `wget` is also used. It will be great to add `wget` into the `brew install` command too.

**Comment by TrungNguyen1909** [comment]
Fixed. thanks.
