### ISSUE TITLE
Stuck on waiting for host to trigger start of restore [timeout of 120 seconds] forever.

### ISSUE THREAD

**Issue by jamesy0ung** [TrungNguyen1909/qemu-t8030#26]
It will be stuck on waiting for host to trigger start of restore [timeout of 120 seconds] forever.

Do I need to run a Linux VM connected to it to run the restore?

(log on pastebin as it is too long for github)
https://pastebin.com/CaC9ZXnF

**Comment by TrungNguyen1909** [comment]
Yes.

**Comment by fatgrass** [comment]
Same error for me. "Yes. You will need a Linux VM if you want to restore." What does this mean? What should I do when I get another Linux VM? Send what command?

**Comment by TrungNguyen1909** [comment]
@fatgrass, Please have a look at [here](https://github.com/TrungNguyen1909/qemu-t8030/wiki/USB-and-Restore).

**Comment by fatgrass** [comment]
> @fatgrass, Please have a look at [here](https://github.com/TrungNguyen1909/qemu-t8030/wiki/USB-and-Restore).

Thanks :)

**Comment by fatgrass** [comment]
> @fatgrass, Please have a look at [here](https://github.com/TrungNguyen1909/qemu-t8030/wiki/USB-and-Restore).

Meet some several compile error when using latest archlinux qcow2 from official site,perhaps some lib version conflict?Will you share a copy of workable archlinux qcow2?
