### ISSUE TITLE
Display and Touch screen support?

### ISSUE THREAD

**Issue by oxemanuelexo** [TrungNguyen1909/qemu-t8030#36]
Has the functionality on the emulated iPhone to be able to see the iPhone display and having a touch screen been implemented yet in this project. And is it possible to emulate iOS using the current instructions on the M1 chip?

**Comment by TrungNguyen1909** [comment]
> Has the functionality on the emulated iPhone to be able to see the iPhone display and having a touch screen been implemented yet in this project

Yes and No. I do have a display implementation that supports the iOS Restore UI locally. However, virtualizing the AGX GPU is required. I am thinking about using the GPU on the M1 chip to achieve this.

> Is it possible to emulate iOS using the current instructions on the M1 chip?
I found 2 ways to interpret this question. The instructions provided in the wiki does works on the M1 chip. Though you might encounter some M1-specific issues. Regarding the ISA, I highly doubt if it is possible to do hardware-accelerated emulation using the M1 cpu.

**Comment by oxemanuelexo** [comment]
So, there is no way at this moment to interact with the display on the emulated iPhone at this moment?

**Comment by TrungNguyen1909** [comment]
pretty much
