### ISSUE TITLE
QEMU Linux VM: 'usb-tcp-remote' is not a valid device model name.

### ISSUE THREAD

**Issue by oxemanuelexo** [TrungNguyen1909/qemu-t8030#38]
When I tried to run a Linux VM running Ubuntu Server in order to do a restore on the emulated iPhone, QEMU returned "qemu-aarch64-softmmu: -device usb-tcp-remote,bus=ehci.0: 'usb-tcp-remote' is not a valid device model name." Is there any way to fix this issue?

**Comment by TrungNguyen1909** [comment]
you also need to use qemu-t8030 for the Linux VM

**Comment by oxemanuelexo** [comment]
I tried to run my Linux vm on QEMu using the following command: 
./qemu-system-aarch64 -machine virt,highmem=off -boot order=c -m 12288 -vga none -device virtio-gpu-pci,xres=640,yres=480 -usb -device usb-ehci,id=ehci -device usb-tcp-remote,bus=ehci.0 -drive file=/Users/emanuelesaladini/Library/Containers/com.utmapp.UTM/Data/Documents/Linux.utm/Images/data.qcow2,cache=writethrough -drive if=pflash,unit=1,file=/Users/emanuelesaladini/Library/Containers/com.utmapp.UTM/Data/Documents/Linux.utm/Images/efi_vars.fd -drive if=pflash,format=raw,unit=0,file=/Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd,readonly=on -monitor telnet:127.0.0.1:1236,server,nowait

But I end up getting a black screen with no boot.
