### ISSUE TITLE
Running iPadOS

### ISSUE THREAD

**Issue by oxemanuelexo** [TrungNguyen1909/qemu-t8030#39]
Is it possible to run iPadOS using this tool?

**Comment by asdfugil** [comment]
You can try using the iPad 9 IPSW (which uses A13 chip), but keep in mind that this emulator emulates an iPhone 11, so it may not work.

**Comment by asdfugil** [comment]
afaik for what this emulator is able to do so far, there is no difference between iOS and iPadOS

**Comment by TrungNguyen1909** [comment]
Probably possible to emulate any A13-based iPads, but at this point, there is no noticeable difference in doing so. I think most iPadOS v. iOS differences are in userspace? no?
