### ISSUE TITLE
Applications Folder Empty

### ISSUE THREAD

**Issue by notos44265** [TrungNguyen1909/qemu-t8030#42]
When booting QEMU Emulation using ramdisk/rootFS method, the file directory /Applications is empty. Did I do something wrong during installation or is it this normal?

**Comment by TrungNguyen1909** [comment]
Yes. If you haven't restored yet. That is completely normal.

**Comment by oxemanuelexo** [comment]
That is happening to me as well, although I have restored it

**Comment by TrungNguyen1909** [comment]
Then chances are you are mounting the ramdisk, not the flash disk.
