### ISSUE TITLE
Linux VM couldn't find the emulated device

### ISSUE THREAD

**Issue by raspiduino** [TrungNguyen1909/qemu-t8030#55]
I followed the instructions in the wiki, build QEMU from this repo, launch a Linux VM using it (I use [Slax](https://slax.org)). I also generated `root_ticket.der` and put it in both host Linux and guess Linux VM, start the Linux VM then start the iOS VM.

The iOS VM boot to the line ```waiting for host to trigger start of restore [timeout of 120 seconds]```
![image](https://user-images.githubusercontent.com/68118236/168983668-fd8dfab3-dd74-4737-a6d0-482d68c4a50e.png)

But Linux VM can't find the device, although it found something using `lsusb`:
![image](https://user-images.githubusercontent.com/68118236/168983620-06546ce8-544c-4ec5-a439-9410c48aadd9.png)

`/tmp/usbqemu` is available in the host:
![image](https://user-images.githubusercontent.com/68118236/168984023-1451a7c0-3e55-45c0-a522-aac007ca1596.png)

When the iOS VM run out of time and reboot, it shows something like `RTBuddy(SMC): WARNING: failed to send ping.`
![image](https://user-images.githubusercontent.com/68118236/168984224-c39d272c-482f-4f69-8439-4bd74c6a9d84.png)

Any ideas? Thanks!

**Comment by TrungNguyen1909** [comment]
are you using the correct qemu for the Linux VM?
You have to use the one built from qemu-t8030 though

**Comment by raspiduino** [comment]
Yes I use `x86_64-softmmu` target from qemu-t8030.

Anyway I found the problem. It's in the Slax OS itself. Switching to another OS (Arch for example) and it will work.

**Comment by raspiduino** [comment]
Wait, I now switched to Debian VM. But now there is another error :((
![image](https://user-images.githubusercontent.com/68118236/169009568-2809cc2d-7b85-4be2-a5ec-09cc641bed3d.png)

(on the left is the iOS VM's serial output, on the right is Linux VM's terminal)

From `idevicerestore`, it said that `ERROR: Unable to discover device type`.

I also hashed the `root_ticket.der` that passed into QEMU and the one in the Linux VM and they are the same (just to check if I copied the wrong version).

What should I do now?

Thanks!

**Comment by TrungNguyen1909** [comment]
Does this happen to idevicerestore commit `17c80a650f963be7842ef15d83e93286a0129f7a` ?

**Comment by raspiduino** [comment]
No, I use `ddc0c16fd876d45ebd92e924c3124772c3a40654` (latest now at the writting time).

**Comment by TrungNguyen1909** [comment]
Ehhh, I don't think you applied the patch correctly

**Comment by raspiduino** [comment]
So how to apply the patch correctly?
And if possible could you build idevicerestore (and its dependencies), then copy these built folders and put them here? Thanks!

**Comment by TrungNguyen1909** [comment]
```diff
diff --git a/src/idevicerestore.c b/src/idevicerestore.c
index b0572ca..b0b6a9e 100644
--- a/src/idevicerestore.c
+++ b/src/idevicerestore.c
@@ -1033,6 +1033,11 @@ int idevicerestore_start(struct idevicerestore_client_t* client)
        }

        idevicerestore_progress(client, RESTORE_STEP_PREPARE, 0.2);
+       if (client->mode == MODE_RESTORE) {
+               if (client->flags & FLAG_ALLOW_RESTORE_MODE) {
+                       tss_enabled = 0;
+               }
+       }

        /* retrieve shsh blobs if required */
        if (tss_enabled) {
diff --git a/src/restore.c b/src/restore.c
index 257cc38..862bb75 100644
--- a/src/restore.c
+++ b/src/restore.c
@@ -302,6 +302,15 @@ irecv_device_t restore_get_irecv_device(struct idevicerestore_client_t* client)
        }

        plist_get_string_val(node, &model);
+       fprintf(stderr, "%s: Found model %s\n", __func__, model);
+
+       /* HACK: Replace DEV devices with AP equivalent devices
+        * So that it can enjoy FDR-less restore
+        */
+       if (strstr(model, "DEV")) {
+               strncpy(strstr(model, "DEV"), "AP\0", 3);
+       }
+
        irecv_devices_get_device_by_hardware_model(model, &irecv_device);
        free(model);
```

Can you try this diff?

**Comment by raspiduino** [comment]
It worked. I need to checkout the commit `17c80a650f963be7842ef15d83e93286a0129f7a` from idevicerestore. I will close this issue, close the pull request in your `qemu-t8030-tools` repo but I think you should edit the wiki to tell people they should patch idevicerestore from the commit `17c80a650f963be7842ef15d83e93286a0129f7a` and build from it.

Good to see it worked!

**Comment by raspiduino** [comment]
I got another weird issue
![image](https://user-images.githubusercontent.com/68118236/169231307-8d96bfab-214a-4614-b98e-a6d6d27220e2.png)

After 120 seconds (even if you are in restore process), the emulator will reboot and cause this.

How to prevent emulator reboot?

Thanks!

**Comment by raspiduino** [comment]
My fault, I use qcow2 disk format instead of raw :)
