### ISSUE TITLE
Booting 16.0b1 restore ramdisk causes "qemu-system-aarch64: macho_parse: Invalid Mach-O object: mh->magic != MACH_MAGIC_64"

### ISSUE THREAD

**Issue by iarchiveml** [TrungNguyen1909/qemu-t8030#62]
I'm getting "qemu-system-aarch64: macho_parse: Invalid Mach-O object: mh->magic != MACH_MAGIC_64" when trying to boot 16.0b1 to restore mode.
Boot command:
../qemu-system-aarch64 -s -M t8030,trustcache-filename=16.0b1/Firmware/078-13778-076.dmg.trustcache,ticket-filename=16.0b1/root_ticket.der \
-kernel 16.0b1/kernelcache.research.iphone12b \
-dtb 16.0b1/Firmware/all_flash/DeviceTree.n104ap.im4p \
-append "debug=0x14e kextlog=0xffff serial=3 -v -restore rd=md0 nand-enable-reformat=1 -progress launchd_missing_exec_no_panic=1" \
-initrd 16.0b1/078-13778-076.dmg \
-cpu max -smp 6 \
-m 4G -serial mon:stdio \
-drive file=20A5283p/nvme.1,format=raw,if=none,id=drive.1 \
-device nvme-ns,drive=drive.1,bus=nvme-bus.0,nsid=1,nstype=1,logical_block_size=4096,physical_block_size=4096 \
-drive file=20A5283p/nvme.2,format=raw,if=none,id=drive.2 \
-device nvme-ns,drive=drive.2,bus=nvme-bus.0,nsid=2,nstype=2,logical_block_size=4096,physical_block_size=4096 \
-drive file=20A5283p/nvme.3,format=raw,if=none,id=drive.3 \
-device nvme-ns,drive=drive.3,bus=nvme-bus.0,nsid=3,nstype=3,logical_block_size=4096,physical_block_size=4096 \
-drive file=20A5283p/nvme.4,format=raw,if=none,id=drive.4 \
-device nvme-ns,drive=drive.4,bus=nvme-bus.0,nsid=4,nstype=4,logical_block_size=4096,physical_block_size=4096 \
-drive file=20A5283p/nvram,if=none,format=raw,id=nvram \
-device apple-nvram,drive=nvram,bus=nvme-bus.0,nsid=5,nstype=5,id=nvram,logical_block_size=4096,physical_block_size=4096 \
-drive file=20A5283p/nvme.6,format=raw,if=none,id=drive.6 \
-device nvme-ns,drive=drive.6,bus=nvme-bus.0,nsid=6,nstype=6,logical_block_size=4096,physical_block_size=4096 \
-drive file=20A5283p/nvme.7,format=raw,if=none,id=drive.7 \
-device nvme-ns,drive=drive.7,bus=nvme-bus.0,nsid=7,nstype=8,logical_block_size=4096,physical_block_size=4096 \
-monitor telnet:127.0.0.1:1235,server,nowait
Full terminal output:
qemu-system-aarch64: macho_parse: Invalid Mach-O object: mh->magic != MACH_MAGIC_64

**Comment by raspiduino** [comment]
How did you build that executable?

**Comment by TrungNguyen1909** [comment]
Fixed on iOS16 branch.
