### ISSUE TITLE
[Question] Android Emulator

### ISSUE THREAD

**Issue by lorenzoferron98** [TrungNguyen1909/qemu-t8030#76]
With this project can I do the same things that I do with Android Emulator? For example can I install app and then use it with UI?

Thanks in advance.

**Comment by TrungNguyen1909** [comment]
We are still a bit far from that

**Comment by lorenzoferron98** [comment]
So when it starts I can see, use or interact with Spribgboard? Or with this project I can use only CLI?

**Comment by TrungNguyen1909** [comment]
Just CLI for now

**Comment by lorenzoferron98** [comment]
Okay, thank you for your explanation.
