### ISSUE TITLE
Compilation failure with Homebrew LLVM on Apple Silicon Mac

### ISSUE THREAD

**Issue by alfiecg24** [TrungNguyen1909/qemu-t8030#87]
On Apple Silicon Macs, running `./configure` where `clang` is at the path `/opt/homebrew/opt/llvm/bin/clang` (installed with `brew install llvm`) will fail. Make sure that users run `export PATH="/usr/bin/:$PATH"` before running `./configure`.

**Comment by TrungNguyen1909** [comment]
Hmmm, I felt like your configuration is weird, since by default, Homebrew LLVM is not linked (keg-only).

**Comment by alfiecg24** [comment]
Ah yes, that will be the reason - sorry about that!
