### ISSUE TITLE
Can we use delete snapshot instead of rename snapshot?

### ISSUE THREAD

**Issue by erjinzhi2333** [TrungNguyen1909/qemu-t8030#90]
Mac os 11.4 without rename apfs snapshot，can we use delete snapshot instead of rename snapshot？

**Comment by TrungNguyen1909** [comment]
I think it should be okay, but I haven't tested that yet.

**Comment by erjinzhi2333** [comment]
it’s okay, tested

**Comment by AlexLearnsToCode** [comment]
@erjinzhi2333  Which file did you mount and how did you delete the snapshot on macOS 11.4?
